services:
#    la_fleur_symfony.example:
#        class: SIO\LaFleurSymfonyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    la_fleur_symfony.panier:
        class: SIO\LaFleurSymfonyBundle\Services\Panier\Panier